### ISSUE TITLE
Support for nested templates

### ISSUE THREAD

**Issue by rfmineguy** [rfmineguy/generics-generator#7]
I think it might be useful to allow you to use other templates within a template.

For example:
A queue implemented with a linked list.

It would be helpful to be able to leverage your existing linked list template in the queue template.

I dont have a great idea on how to support this yet, but I think its a good feature to remember.

**Comment by rfmineguy** [comment]
NOTE: Recursive templates should not be allowed

**Comment by rfmineguy** [comment]
Potential format

```toml
name = "queue"
generators = ["queue.htpl", "queue.ctpl"]
outformat = "queue_T"

[deps.linked_list.forward]
datatype = "$T"

[args.datatype-name]
symbol = "$T"

[args.datatype-type]
symbol = "@T"

[args.free]
symbol = "FREE"
default = "free"

[args.print]
symbol = "PRINT"
default = "printf"

[args.calloc]
symbol = "CALLOC"
default = "calloc"

[args.realloc]
symbol = "REALLOC"
default = "realloc"

[args.header]
symbol = "HEADER_INCLUDE"
default = "stdint.h"
```

**Comment by rfmineguy** [comment]
More complex example (that doesn't make realistic sense, but demonstrates the idea)

```toml
name = "queue"
generators = ["queue.htpl", "queue.ctpl"]
outformat = "queue_T"

[deps.linked_list.forward]
datatype = "datatype-name"

[deps.vector.forward]
datatype = "datatype-name"

[args.datatype-name]
symbol = "$T"

[args.datatype-type]
symbol = "@T"

[args.free]
symbol = "FREE"
default = "free"

[args.print]
symbol = "PRINT"
default = "printf"

[args.calloc]
symbol = "CALLOC"
default = "calloc"

[args.realloc]
symbol = "REALLOC"
default = "realloc"

[args.header]
symbol = "HEADER_INCLUDE"
default = "stdint.h"
```
